-- for h2
INSERT INTO quotes (request_no, owner,item, description, requested_by,category,item_class,division,brand,dept,buyer,hts_no,	request_price,currency,delivery_terms,import_cntry,allocated_qty,modify_ts,modify_user) VALUES (NEXT VALUE FOR REQUESTS_NO_SEQ, 'BAMBOOROSE','Cheese','Food Ingresdient','Lun Yi','Food','first','food',	'Stop-Shop','Food',	'Vendor','AOA',100.00,	'USD',	'AIR',	'US',1000,	NULL, 'Lun Yi');
INSERT INTO offers (offer_no, owner,request_no, item, offer_date, supplier, currency,payment_type,  payment_terms,delivery_terms, origin_cntry,lading_point, first_ship_date, last_ship_date, buyer, final_dest) select NEXT VALUE FOR OFFERS_NO_SEQ, 'BAMBOOROSE', max(request_no),'Cheese', '2020-01-01', 'Stop-Shop', 'USD','Cash', 'COD', 'FCA',  'USA', 'Boston',   NULL, '2020-11-01', 'Divid', 'China' from quotes;

INSERT INTO quotes (request_no,  owner,item, description,requested_by,category,item_class,division,brand,dept,buyer,hts_no,request_price,currency,delivery_terms,import_cntry,allocated_qty,modify_ts,modify_user) VALUES (NEXT VALUE FOR REQUESTS_NO_SEQ, 'BAMBOOROSE','Pork Shoulder','Food','Lun Yi','Food','first','food','Stop-Shop','Food','Vendor','AOA',100.00,'USD','AIR','US',1000, NULL, 'Lun Yi');

INSERT INTO offers (offer_no, owner,request_no, item, offer_date, supplier, currency,payment_type,  payment_terms,delivery_terms,origin_cntry,lading_point, first_ship_date, last_ship_date, buyer,final_dest) select NEXT VALUE FOR OFFERS_NO_SEQ, 'BAMBOOROSE', max(request_no), 'Pork Shoulder', NULL, 'Stop-Shop', 'USD','Cash', 'COD', 'FCA', 'USA', 'CT', null,  '2020-11-2', 'Peter', 'India'  from quotes;

INSERT INTO orders (order_no, order_date, tot_grs_value, tot_calc_cost, tot_qty, tot_grs_wgt, offer_no, owner, item,  supplier, currency,payment_type,  payment_terms,delivery_terms, origin_cntry,lading_point, first_ship_date, last_ship_date, buyer,final_dest) select NEXT VALUE FOR ORDERS_NO_SEQ, '2020-11-01', 1005, 105, 10005, 285, max(offer_no),  'BAMBOOROSE', 'Cheese', 'Stop-Shop', 'USD','Cash', 'COD', 'FCA',  'USA', 'Boston', '2020-11-02', null, 'David','China' from offers;

INSERT INTO orders (order_no, order_date, tot_grs_value, tot_calc_cost, tot_qty, tot_grs_wgt, offer_no, owner, item,  supplier, currency,payment_type,  payment_terms,delivery_terms,origin_cntry,lading_point, first_ship_date, last_ship_date, buyer,final_dest) select NEXT VALUE FOR ORDERS_NO_SEQ, '2020-11-02', 1000, 100, 10000, 280, max(offer_no),  'BAMBOOROSE',  'Pork Shoulder', 'Stop-Shop', 'USD','Cash', 'COD', 'FCA',  'USA', 'CT','2020-11-03',  null, 'Peter','India' from offers;


-- for postgresql
--INSERT INTO quotes (request_no, owner,item, description, requested_by,category,item_class,division,brand,dept,buyer,hts_no,	request_price,currency,delivery_terms,import_cntry,allocated_qty,modify_ts,modify_user) VALUES (nextval('REQUESTS_NO_SEQ'), 'BAMBOOROSE','Cheese','Food Ingresdient','Lun Yi','Food','first','food',	'Stop-Shop','Food',	'Vendor','AOA',100.00,	'USD',	'AIR',	'US',1000,	NULL, 'Lun Yi');
--INSERT INTO offers (offer_no, owner,request_no, item, offer_date, supplier, currency,payment_type,  payment_terms,delivery_terms, origin_cntry,lading_point, first_ship_date, last_ship_date, buyer,final_dest) select nextval('OFFERS_NO_SEQ'), 'BAMBOOROSE', max(request_no),'Cheese', '2020-01-01', 'Stop-Shop', 'USD','Cash', 'COD', 'FCA',  'USA', 'Boston',   NULL, '2020-11-01', 'David', 'China' from quotes;

--INSERT INTO quotes (request_no,  owner,item, description,requested_by,category,item_class,division,brand,dept,buyer,hts_no,request_price,currency,delivery_terms,import_cntry,allocated_qty,modify_ts,modify_user) VALUES (nextval('REQUESTS_NO_SEQ'), 'BAMBOOROSE','Pork Shoulder','Food','Lun Yi','Food','first','food','Stop-Shop','Food','Vendor','AOA',100.00,'USD','AIR','US',1000, NULL, 'Lun Yi');

--INSERT INTO offers (offer_no, owner,request_no, item, offer_date, supplier, currency,payment_type,  payment_terms,delivery_terms,origin_cntry,lading_point, first_ship_date, last_ship_date, buyer,final_dest) select nextval('OFFERS_NO_SEQ'), 'BAMBOOROSE', max(request_no), 'Pork Shoulder', NULL, 'Stop-Shop', 'USD','Cash', 'COD', 'FCA', 'USA', 'CT', null,  '2020-11-2', 'Peter', 'India'  from quotes;

--INSERT INTO orders (order_no, order_date, tot_grs_value, tot_calc_cost, tot_qty, tot_grs_wgt, offer_no, owner, item,  supplier, currency,payment_type,  payment_terms,delivery_terms, origin_cntry,lading_point, first_ship_date, last_ship_date, buyer,final_dest) select nextval('ORDERS_NO_SEQ'), '2020-11-01', 1005, 105, 10005, 285, max(offer_no),  'BAMBOOROSE', 'Cheese', 'Stop-Shop', 'USD','Cash', 'COD', 'FCA',  'USA', 'Boston', '2020-11-02', null, 'David', 'China' from offers;

--INSERT INTO orders (order_no, order_date, tot_grs_value, tot_calc_cost, tot_qty, tot_grs_wgt, offer_no, owner, item,  supplier, currency,payment_type,  payment_terms,delivery_terms,origin_cntry,lading_point, first_ship_date, last_ship_date, buyer,final_dest) select nextval('ORDERS_NO_SEQ'), '2020-11-02', 1000, 100, 10000, 280, max(offer_no),  'BAMBOOROSE',  'Pork Shoulder', 'Stop-Shop', 'USD','Cash', 'COD', 'FCA',  'USA', 'CT','2020-11-03',  null, 'Peter', 'India' from offers;
